var search={
  "Achterkastell": "http://data.archaeology.link/data/maritimethesaurus/644D77",
  "Achterschiff": "http://data.archaeology.link/data/maritimethesaurus/4277CC",
  "Achtersteven": "http://data.archaeology.link/data/maritimethesaurus/938B4F",
  "Anker": "http://data.archaeology.link/data/maritimethesaurus/7EA68E",
  "Anriss": "http://data.archaeology.link/data/maritimethesaurus/5B0B41",
  "Arbeitsboot": "http://data.archaeology.link/data/maritimethesaurus/D7F183",
  "Artillerie": "http://data.archaeology.link/data/maritimethesaurus/15087C",
  "Auflanger": "http://data.archaeology.link/data/maritimethesaurus/F0F917",
  "Ausleger": "http://data.archaeology.link/data/maritimethesaurus/379A2E",
  "Aussensteven (hinten)": "http://data.archaeology.link/data/maritimethesaurus/A7A73E",
  "Aussparung": "http://data.archaeology.link/data/maritimethesaurus/5601F3",
  "Balken": "http://data.archaeology.link/data/maritimethesaurus/7ED321",
  "Bargholz": "http://data.archaeology.link/data/maritimethesaurus/B0565D",
  "Beplankung": "http://data.archaeology.link/data/maritimethesaurus/F71E8E",
  "Beschlag": "http://data.archaeology.link/data/maritimethesaurus/03297B",
  "Bilgerinne": "http://data.archaeology.link/data/maritimethesaurus/2215C5",
  "Binnenland": "http://data.archaeology.link/data/maritimethesaurus/E0984E",
  "Blackfriars": "http://data.archaeology.link/data/maritimethesaurus/A21BCC",
  "Block": "http://data.archaeology.link/data/maritimethesaurus/FB341B",
  "Blockade": "http://data.archaeology.link/data/maritimethesaurus/C4AA6D",
  "Boden": "http://data.archaeology.link/data/maritimethesaurus/3A3C90",
  "Boden zuerst": "http://data.archaeology.link/data/maritimethesaurus/610FD3",
  "Bodenplanke": "http://data.archaeology.link/data/maritimethesaurus/09DF17",
  "Bohrung": "http://data.archaeology.link/data/maritimethesaurus/4744EE",
  "Bolzen": "http://data.archaeology.link/data/maritimethesaurus/54D771",
  "Bolzen (Bronze)": "http://data.archaeology.link/data/maritimethesaurus/CEA053",
  "Bolzen (Eisen)": "http://data.archaeology.link/data/maritimethesaurus/2A2031",
  "Brigg": "http://data.archaeology.link/data/maritimethesaurus/239F9C",
  "Bug": "http://data.archaeology.link/data/maritimethesaurus/87FFFB",
  "Bug Sprit": "http://data.archaeology.link/data/maritimethesaurus/411EC9",
  "Bugholz": "http://data.archaeology.link/data/maritimethesaurus/E9E384",
  "Bugsporn": "http://data.archaeology.link/data/maritimethesaurus/45B061",
  "B\u00fcnte": "http://data.archaeology.link/data/maritimethesaurus/B5BA3D",
  "Deck": "http://data.archaeology.link/data/maritimethesaurus/61AB9E",
  "Decksbalken": "http://data.archaeology.link/data/maritimethesaurus/0BE8C2",
  "Decksplanke": "http://data.archaeology.link/data/maritimethesaurus/817F57",
  "Dekoration": "http://data.archaeology.link/data/maritimethesaurus/1EB740",
  "Dollbaum": "http://data.archaeology.link/data/maritimethesaurus/8AFF10",
  "Dollbord": "http://data.archaeology.link/data/maritimethesaurus/D1CB84",
  "Dolle": "http://data.archaeology.link/data/maritimethesaurus/D8EF0C",
  "Dover": "http://data.archaeology.link/data/maritimethesaurus/26941E",
  "Duchtst\u00fctze": "http://data.archaeology.link/data/maritimethesaurus/9A4CAE",
  "Einbaum": "http://data.archaeology.link/data/maritimethesaurus/D88694",
  "Einbaum (Boden)": "http://data.archaeology.link/data/maritimethesaurus/C0B0E1",
  "Einbaum (erweitert)": "http://data.archaeology.link/data/maritimethesaurus/BAED73",
  "Einbaum (mit Gesamtdeck)": "http://data.archaeology.link/data/maritimethesaurus/427FCF",
  "Einbaum (mit Vorunter)": "http://data.archaeology.link/data/maritimethesaurus/E0BC8C",
  "Erweiterter Einbaum": "http://data.archaeology.link/data/maritimethesaurus/EAD7A9",
  "Fischereifahrzeug": "http://data.archaeology.link/data/maritimethesaurus/8D23B1",
  "Flickung": "http://data.archaeology.link/data/maritimethesaurus/A6A046",
  "Frachter": "http://data.archaeology.link/data/maritimethesaurus/C5A0B6",
  "Funktion unbekannt": "http://data.archaeology.link/data/maritimethesaurus/2FF7C7",
  "Futterholz": "http://data.archaeology.link/data/maritimethesaurus/A00109",
  "Gang": "http://data.archaeology.link/data/maritimethesaurus/47191C",
  "Geklinkert": "http://data.archaeology.link/data/maritimethesaurus/1F8C94",
  "Gen\u00e4ht": "http://data.archaeology.link/data/maritimethesaurus/CFCC18",
  "Gepaddelt": "http://data.archaeology.link/data/maritimethesaurus/BC75BB",
  "Gepaddelt und gesegelt": "http://data.archaeology.link/data/maritimethesaurus/1E27F0",
  "Gerudert": "http://data.archaeology.link/data/maritimethesaurus/7B12A2",
  "Gerudert und gesegelt": "http://data.archaeology.link/data/maritimethesaurus/947F7A",
  "Gerudert, gestakt und gesegelt": "http://data.archaeology.link/data/maritimethesaurus/C7A87C",
  "Gesegelt": "http://data.archaeology.link/data/maritimethesaurus/B3B8F9",
  "Gestakt": "http://data.archaeology.link/data/maritimethesaurus/0A8516",
  "Gestakt und gesegelt": "http://data.archaeology.link/data/maritimethesaurus/346DF1",
  "Getreidelt": "http://data.archaeology.link/data/maritimethesaurus/705DB7",
  "Getreidelt und gepaddelt": "http://data.archaeology.link/data/maritimethesaurus/5ED27C",
  "Getreidelt und gesegelt": "http://data.archaeology.link/data/maritimethesaurus/E5EF06",
  "Gut (Laufend)": "http://data.archaeology.link/data/maritimethesaurus/8C0C1B",
  "Gut (Stehend)": "http://data.archaeology.link/data/maritimethesaurus/074F8A",
  "Halbspant": "http://data.archaeology.link/data/maritimethesaurus/C4B24F",
  "Heck": "http://data.archaeology.link/data/maritimethesaurus/DB6446",
  "Holznagel": "http://data.archaeology.link/data/maritimethesaurus/B8ECB5",
  "Holzstift": "http://data.archaeology.link/data/maritimethesaurus/EB6A4F",
  "Jungfer-Block": "http://data.archaeology.link/data/maritimethesaurus/178A10",
  "Kabine": "http://data.archaeology.link/data/maritimethesaurus/9DF75C",
  "Kaffe": "http://data.archaeology.link/data/maritimethesaurus/7F16E0",
  "Kalfat": "http://data.archaeology.link/data/maritimethesaurus/88C1CD",
  "Kanuausleger": "http://data.archaeology.link/data/maritimethesaurus/3C3311",
  "Keipe": "http://data.archaeology.link/data/maritimethesaurus/4B0A52",
  "Kiel": "http://data.archaeology.link/data/maritimethesaurus/20F045",
  "Kielgang": "http://data.archaeology.link/data/maritimethesaurus/29CBC9",
  "Kielplanke": "http://data.archaeology.link/data/maritimethesaurus/F426DE",
  "Kielschwein": "http://data.archaeology.link/data/maritimethesaurus/20AB84",
  "Kimm (Eckig)": "http://data.archaeology.link/data/maritimethesaurus/977C4D",
  "Kimm (Rund)": "http://data.archaeology.link/data/maritimethesaurus/5E0D28",
  "Kimmholz": "http://data.archaeology.link/data/maritimethesaurus/09BEBF",
  "Kimmstringer": "http://data.archaeology.link/data/maritimethesaurus/0D16A2",
  "Klampe": "http://data.archaeology.link/data/maritimethesaurus/403A13",
  "Klinker (Seite)": "http://data.archaeology.link/data/maritimethesaurus/6C1C1D",
  "Knie": "http://data.archaeology.link/data/maritimethesaurus/434F04",
  "Kraweel (Beplankung)": "http://data.archaeology.link/data/maritimethesaurus/2C6BDB",
  "Kraweel (Boden)": "http://data.archaeology.link/data/maritimethesaurus/EAC98D",
  "Kraweel (Seite)": "http://data.archaeology.link/data/maritimethesaurus/6491C3",
  "Kraweel Beplankt": "http://data.archaeology.link/data/maritimethesaurus/1C41AC",
  "K\u00fcste": "http://data.archaeology.link/data/maritimethesaurus/7D2D8B",
  "Langschiff": "http://data.archaeology.link/data/maritimethesaurus/DC89EB",
  "Laufplanke": "http://data.archaeology.link/data/maritimethesaurus/10E2CF",
  "Lukendeckel": "http://data.archaeology.link/data/maritimethesaurus/EF0C63",
  "L\u00e4ngsversteifung": "http://data.archaeology.link/data/maritimethesaurus/3FBE29",
  "Mainz A": "http://data.archaeology.link/data/maritimethesaurus/40D1A3",
  "Mainz B": "http://data.archaeology.link/data/maritimethesaurus/ABFB76",
  "Mallenbauweise": "http://data.archaeology.link/data/maritimethesaurus/FF8A47",
  "Mast (Besanmast)": "http://data.archaeology.link/data/maritimethesaurus/655F73",
  "Mast (Hauptmast)": "http://data.archaeology.link/data/maritimethesaurus/FE0706",
  "Mast (Vormast)": "http://data.archaeology.link/data/maritimethesaurus/69600C",
  "Mastbalken": "http://data.archaeology.link/data/maritimethesaurus/2143CF",
  "Mastbereich": "http://data.archaeology.link/data/maritimethesaurus/AF5C8D",
  "Mastducht": "http://data.archaeology.link/data/maritimethesaurus/D12C93",
  "Mastfisch": "http://data.archaeology.link/data/maritimethesaurus/1C43CA",
  "Mastspant": "http://data.archaeology.link/data/maritimethesaurus/1C9D25",
  "Mastspur": "http://data.archaeology.link/data/maritimethesaurus/2B8C74",
  "Mastst\u00fctze": "http://data.archaeology.link/data/maritimethesaurus/B0D70E",
  "Masttopp": "http://data.archaeology.link/data/maritimethesaurus/1F4820",
  "Milit\u00e4rfahrzeug": "http://data.archaeology.link/data/maritimethesaurus/8B55C4",
  "Mittelsteven": "http://data.archaeology.link/data/maritimethesaurus/8CA594",
  "NAVISone Maritime Thesaurus": "http://data.archaeology.link/data/maritimethesaurus/cs01",
  "Nagel": "http://data.archaeology.link/data/maritimethesaurus/1D1955",
  "Nagel (Baum)": "http://data.archaeology.link/data/maritimethesaurus/7393C9",
  "Nagel (Bronze)": "http://data.archaeology.link/data/maritimethesaurus/BC332F",
  "Nagel (Kupfer)": "http://data.archaeology.link/data/maritimethesaurus/8FCA50",
  "Naht": "http://data.archaeology.link/data/maritimethesaurus/6471C5",
  "Nahtspant": "http://data.archaeology.link/data/maritimethesaurus/431A1E",
  "Navis caudicaria": "http://data.archaeology.link/data/maritimethesaurus/3323FF",
  "Navis oneraria": "http://data.archaeology.link/data/maritimethesaurus/C42DC4",
  "Niet": "http://data.archaeology.link/data/maritimethesaurus/C11F67",
  "Nordic": "http://data.archaeology.link/data/maritimethesaurus/FD7D75",
  "North Ferriby": "http://data.archaeology.link/data/maritimethesaurus/4EC602",
  "Nut und Feder": "http://data.archaeology.link/data/maritimethesaurus/D3FF82",
  "Obersporn": "http://data.archaeology.link/data/maritimethesaurus/BE91AE",
  "Oberstimm": "http://data.archaeology.link/data/maritimethesaurus/ED5180",
  "Paddel": "http://data.archaeology.link/data/maritimethesaurus/75D305",
  "Papyrusboot": "http://data.archaeology.link/data/maritimethesaurus/B2CF95",
  "Planke": "http://data.archaeology.link/data/maritimethesaurus/C71032",
  "Plankenbeschlag": "http://data.archaeology.link/data/maritimethesaurus/D59DA1",
  "Poller": "http://data.archaeology.link/data/maritimethesaurus/98614C",
  "Pommeroeul 1": "http://data.archaeology.link/data/maritimethesaurus/C8BE01",
  "Querriegel": "http://data.archaeology.link/data/maritimethesaurus/FE767B",
  "Rack": "http://data.archaeology.link/data/maritimethesaurus/EDB704",
  "Rad": "http://data.archaeology.link/data/maritimethesaurus/1975C4",
  "Rah": "http://data.archaeology.link/data/maritimethesaurus/1149D5",
  "Rammsporn": "http://data.archaeology.link/data/maritimethesaurus/A3EBFA",
  "Reling": "http://data.archaeology.link/data/maritimethesaurus/5EF232",
  "Riemen": "http://data.archaeology.link/data/maritimethesaurus/DCA950",
  "Riemenpforte": "http://data.archaeology.link/data/maritimethesaurus/A3C7CB",
  "Ruder (Heck)": "http://data.archaeology.link/data/maritimethesaurus/5F47CB",
  "Ruderbalken": "http://data.archaeology.link/data/maritimethesaurus/807A0F",
  "Ruderbalken St\u00fctze": "http://data.archaeology.link/data/maritimethesaurus/737BE7",
  "Ruderducht (Sitz)": "http://data.archaeology.link/data/maritimethesaurus/A1A0DE",
  "Ruderfassung": "http://data.archaeology.link/data/maritimethesaurus/3A4334",
  "Ruderpinne": "http://data.archaeology.link/data/maritimethesaurus/FBE946",
  "Ruderverblendung": "http://data.archaeology.link/data/maritimethesaurus/02A954",
  "Rute": "http://data.archaeology.link/data/maritimethesaurus/85C3C2",
  "Schale": "http://data.archaeology.link/data/maritimethesaurus/0093DC",
  "Schalenbauweise": "http://data.archaeology.link/data/maritimethesaurus/690B73",
  "Schandeckel": "http://data.archaeology.link/data/maritimethesaurus/DC8396",
  "Schanzkleid": "http://data.archaeology.link/data/maritimethesaurus/B61EB9",
  "Scheuerleiste": "http://data.archaeology.link/data/maritimethesaurus/A9FE4D",
  "Schild": "http://data.archaeology.link/data/maritimethesaurus/DB88D4",
  "Schildhalterung": "http://data.archaeology.link/data/maritimethesaurus/D060C4",
  "Schnur": "http://data.archaeology.link/data/maritimethesaurus/A46547",
  "Schott": "http://data.archaeology.link/data/maritimethesaurus/A1B3F9",
  "Sch\u00e4ftung": "http://data.archaeology.link/data/maritimethesaurus/49AA0C",
  "See": "http://data.archaeology.link/data/maritimethesaurus/2EA1AB",
  "Segel (Lateiner)": "http://data.archaeology.link/data/maritimethesaurus/441BAE",
  "Segel (Rah)": "http://data.archaeology.link/data/maritimethesaurus/F4405C",
  "Segel (Sprit)": "http://data.archaeology.link/data/maritimethesaurus/0E4547",
  "Seitenspant": "http://data.archaeology.link/data/maritimethesaurus/5F88DE",
  "Seitensteven": "http://data.archaeology.link/data/maritimethesaurus/130F84",
  "Skelettbauweise": "http://data.archaeology.link/data/maritimethesaurus/BD12D8",
  "Spant": "http://data.archaeology.link/data/maritimethesaurus/06BE5F",
  "Spiegel": "http://data.archaeology.link/data/maritimethesaurus/CDC760",
  "Sponung": "http://data.archaeology.link/data/maritimethesaurus/3DE001",
  "Sprung": "http://data.archaeology.link/data/maritimethesaurus/BCE269",
  "Stakstange": "http://data.archaeology.link/data/maritimethesaurus/4FF277",
  "Steuerruder": "http://data.archaeology.link/data/maritimethesaurus/2D4862",
  "Stevendekoration": "http://data.archaeology.link/data/maritimethesaurus/D10A1D",
  "Stevenschuh/Anlauf": "http://data.archaeology.link/data/maritimethesaurus/AC3D96",
  "Stringer": "http://data.archaeology.link/data/maritimethesaurus/EB04DC",
  "St\u00fctze": "http://data.archaeology.link/data/maritimethesaurus/AF72E8",
  "Tau": "http://data.archaeology.link/data/maritimethesaurus/F9BB92",
  "Toppsegel": "http://data.archaeology.link/data/maritimethesaurus/648E0B",
  "Totgang": "http://data.archaeology.link/data/maritimethesaurus/0B9A28",
  "Treidelpfosten": "http://data.archaeology.link/data/maritimethesaurus/2AC165",
  "Typ Blussus": "http://data.archaeology.link/data/maritimethesaurus/F48592",
  "Typ Igel": "http://data.archaeology.link/data/maritimethesaurus/67C5EA",
  "Typ Neumagen": "http://data.archaeology.link/data/maritimethesaurus/AC906A",
  "Typ Portus": "http://data.archaeology.link/data/maritimethesaurus/B0F013",
  "Unbekannt": "http://data.archaeology.link/data/maritimethesaurus/D800BA",
  "Unbekannte Konstruktion": "http://data.archaeology.link/data/maritimethesaurus/619AD3",
  "Unbekannter Antrieb": "http://data.archaeology.link/data/maritimethesaurus/A14DDA",
  "Unbekannter Schiffstyp": "http://data.archaeology.link/data/maritimethesaurus/883E8D",
  "Utrecht 1": "http://data.archaeology.link/data/maritimethesaurus/6A2A87",
  "Utrecht 3": "http://data.archaeology.link/data/maritimethesaurus/0234D3",
  "Vorderkastell": "http://data.archaeology.link/data/maritimethesaurus/B6D026",
  "Vordersteven": "http://data.archaeology.link/data/maritimethesaurus/B0535D",
  "Vorschiff": "http://data.archaeology.link/data/maritimethesaurus/80B562",
  "Vorsegel": "http://data.archaeology.link/data/maritimethesaurus/71CB9C",
  "Waffen": "http://data.archaeology.link/data/maritimethesaurus/9416B4",
  "Wegerung": "http://data.archaeology.link/data/maritimethesaurus/D03311",
  "Werkzeugspur": "http://data.archaeology.link/data/maritimethesaurus/AFF00C",
  "Winde": "http://data.archaeology.link/data/maritimethesaurus/C399D6",
  "Woerden 1": "http://data.archaeology.link/data/maritimethesaurus/679A09",
  "Woerden 2": "http://data.archaeology.link/data/maritimethesaurus/B02E91",
  "Wrange": "http://data.archaeology.link/data/maritimethesaurus/5EEC61",
  "Zimmermannszeichen": "http://data.archaeology.link/data/maritimethesaurus/AB357C",
  "Zwammerdam": "http://data.archaeology.link/data/maritimethesaurus/D6F501",
  "Zwammerdam 3": "http://data.archaeology.link/data/maritimethesaurus/96911B",
  "Zwammerdam 5": "http://data.archaeology.link/data/maritimethesaurus/51C929",
  "[Antrieb]": "http://data.archaeology.link/data/maritimethesaurus/1003",
  "[Arbeitsumgebung]": "http://data.archaeology.link/data/maritimethesaurus/1002",
  "[Aufbauten]": "http://data.archaeology.link/data/maritimethesaurus/1019",
  "[Besegelung]": "http://data.archaeology.link/data/maritimethesaurus/1010",
  "[Decks und Weger]": "http://data.archaeology.link/data/maritimethesaurus/1008",
  "[Handhabung]": "http://data.archaeology.link/data/maritimethesaurus/1014",
  "[Innenkonstruktion]": "http://data.archaeology.link/data/maritimethesaurus/1007",
  "[Konstruktionsmerkmale]": "http://data.archaeology.link/data/maritimethesaurus/1009",
  "[Kriegsf\u00fchrung]": "http://data.archaeology.link/data/maritimethesaurus/1015",
  "[Oberfl\u00e4chenbehandlung]": "http://data.archaeology.link/data/maritimethesaurus/1016",
  "[Ruderanlage]": "http://data.archaeology.link/data/maritimethesaurus/1011",
  "[Rudern und paddeln]": "http://data.archaeology.link/data/maritimethesaurus/1012",
  "[Rumpf]": "http://data.archaeology.link/data/maritimethesaurus/1006",
  "[Schiffsfunktion]": "http://data.archaeology.link/data/maritimethesaurus/1001",
  "[Schiffstyp]": "http://data.archaeology.link/data/maritimethesaurus/1004",
  "[Staken und treideln]": "http://data.archaeology.link/data/maritimethesaurus/1013",
  "falscher Kiel": "http://data.archaeology.link/data/maritimethesaurus/B00683",
  "galeeren\u00e4hnlich": "http://data.archaeology.link/data/maritimethesaurus/AB5CBB",
  "gebunden": "http://data.archaeology.link/data/maritimethesaurus/A29AEA",
  "hulk\u00e4hnlich": "http://data.archaeology.link/data/maritimethesaurus/5472B2",
  "koggen\u00e4hnlich": "http://data.archaeology.link/data/maritimethesaurus/63A6E4",
  "n\u00fcstergatt": "http://data.archaeology.link/data/maritimethesaurus/D81709",
  "prahm\u00e4hnlich": "http://data.archaeology.link/data/maritimethesaurus/8E26B8",
  "wikingerschiff\u00e4hnlich": "http://data.archaeology.link/data/maritimethesaurus/54E32C"
}