var search={
  "Achterkastell": "http://data.archaeology.link/data/maritimethesaurus/8D2DDA",
  "Achterschiff": "http://data.archaeology.link/data/maritimethesaurus/69E39F",
  "Achtersteven": "http://data.archaeology.link/data/maritimethesaurus/04107E",
  "Anker": "http://data.archaeology.link/data/maritimethesaurus/61FA94",
  "Anriss": "http://data.archaeology.link/data/maritimethesaurus/DD168D",
  "Arbeitsboot": "http://data.archaeology.link/data/maritimethesaurus/7F0E2B",
  "Artillerie": "http://data.archaeology.link/data/maritimethesaurus/9F24E8",
  "Auflanger": "http://data.archaeology.link/data/maritimethesaurus/067FCD",
  "Ausleger": "http://data.archaeology.link/data/maritimethesaurus/3603E6",
  "Aussensteven (hinten)": "http://data.archaeology.link/data/maritimethesaurus/89290D",
  "Aussparung": "http://data.archaeology.link/data/maritimethesaurus/5244B7",
  "Balken": "http://data.archaeology.link/data/maritimethesaurus/97C594",
  "Bargholz": "http://data.archaeology.link/data/maritimethesaurus/E7AD7A",
  "Beplankung": "http://data.archaeology.link/data/maritimethesaurus/9A860E",
  "Beschlag": "http://data.archaeology.link/data/maritimethesaurus/BDA98D",
  "Bilgerinne": "http://data.archaeology.link/data/maritimethesaurus/EF438D",
  "Binnenland": "http://data.archaeology.link/data/maritimethesaurus/1243AD",
  "Blackfriars": "http://data.archaeology.link/data/maritimethesaurus/F6F407",
  "Block": "http://data.archaeology.link/data/maritimethesaurus/B173C4",
  "Blockade": "http://data.archaeology.link/data/maritimethesaurus/576903",
  "Boden": "http://data.archaeology.link/data/maritimethesaurus/06DF49",
  "Boden zuerst": "http://data.archaeology.link/data/maritimethesaurus/71575D",
  "Bodenplanke": "http://data.archaeology.link/data/maritimethesaurus/16ED34",
  "Bohrung": "http://data.archaeology.link/data/maritimethesaurus/E8B19E",
  "Bolzen": "http://data.archaeology.link/data/maritimethesaurus/C0C8D3",
  "Bolzen (Bronze)": "http://data.archaeology.link/data/maritimethesaurus/CD6133",
  "Bolzen (Eisen)": "http://data.archaeology.link/data/maritimethesaurus/FD5EF1",
  "Brigg": "http://data.archaeology.link/data/maritimethesaurus/81CB47",
  "Bug": "http://data.archaeology.link/data/maritimethesaurus/42300A",
  "Bug Sprit": "http://data.archaeology.link/data/maritimethesaurus/E3A2EB",
  "Bugholz": "http://data.archaeology.link/data/maritimethesaurus/CCEBB1",
  "Bugsporn": "http://data.archaeology.link/data/maritimethesaurus/36E638",
  "B\u00fcnte": "http://data.archaeology.link/data/maritimethesaurus/18D039",
  "Deck": "http://data.archaeology.link/data/maritimethesaurus/0C22DB",
  "Decksbalken": "http://data.archaeology.link/data/maritimethesaurus/CFD0AB",
  "Decksplanke": "http://data.archaeology.link/data/maritimethesaurus/78C8CF",
  "Dekoration": "http://data.archaeology.link/data/maritimethesaurus/6097B3",
  "Dollbaum": "http://data.archaeology.link/data/maritimethesaurus/B876C5",
  "Dollbord": "http://data.archaeology.link/data/maritimethesaurus/4B5BF3",
  "Dolle": "http://data.archaeology.link/data/maritimethesaurus/6EDC6E",
  "Dover": "http://data.archaeology.link/data/maritimethesaurus/F7285A",
  "Duchtst\u00fctze": "http://data.archaeology.link/data/maritimethesaurus/1B5D3C",
  "Einbaum": "http://data.archaeology.link/data/maritimethesaurus/9DDCA0",
  "Einbaum (Boden)": "http://data.archaeology.link/data/maritimethesaurus/01390D",
  "Einbaum (erweitert)": "http://data.archaeology.link/data/maritimethesaurus/BBCBE0",
  "Einbaum (mit Gesamtdeck)": "http://data.archaeology.link/data/maritimethesaurus/0AD305",
  "Einbaum (mit Vorunter)": "http://data.archaeology.link/data/maritimethesaurus/4E64BF",
  "Erweiterter Einbaum": "http://data.archaeology.link/data/maritimethesaurus/03AC7B",
  "Fischereifahrzeug": "http://data.archaeology.link/data/maritimethesaurus/C5E744",
  "Flickung": "http://data.archaeology.link/data/maritimethesaurus/95D183",
  "Frachter": "http://data.archaeology.link/data/maritimethesaurus/AD63B1",
  "Funktion unbekannt": "http://data.archaeology.link/data/maritimethesaurus/E3362C",
  "Futterholz": "http://data.archaeology.link/data/maritimethesaurus/615494",
  "Gang": "http://data.archaeology.link/data/maritimethesaurus/3E71D2",
  "Geklinkert": "http://data.archaeology.link/data/maritimethesaurus/A5749D",
  "Gen\u00e4ht": "http://data.archaeology.link/data/maritimethesaurus/F2A43F",
  "Gepaddelt": "http://data.archaeology.link/data/maritimethesaurus/9F7CCE",
  "Gepaddelt und gesegelt": "http://data.archaeology.link/data/maritimethesaurus/1CE7AB",
  "Gerudert": "http://data.archaeology.link/data/maritimethesaurus/79B1BE",
  "Gerudert und gesegelt": "http://data.archaeology.link/data/maritimethesaurus/065516",
  "Gerudert, gestakt und gesegelt": "http://data.archaeology.link/data/maritimethesaurus/CF76BE",
  "Gesegelt": "http://data.archaeology.link/data/maritimethesaurus/A3F19E",
  "Gestakt": "http://data.archaeology.link/data/maritimethesaurus/959CF0",
  "Gestakt und gesegelt": "http://data.archaeology.link/data/maritimethesaurus/662AD8",
  "Getreidelt": "http://data.archaeology.link/data/maritimethesaurus/E86A62",
  "Getreidelt und gepaddelt": "http://data.archaeology.link/data/maritimethesaurus/FA4000",
  "Getreidelt und gesegelt": "http://data.archaeology.link/data/maritimethesaurus/970E41",
  "Gut (Laufend)": "http://data.archaeology.link/data/maritimethesaurus/9C7A8F",
  "Gut (Stehend)": "http://data.archaeology.link/data/maritimethesaurus/E3C0E8",
  "Halbspant": "http://data.archaeology.link/data/maritimethesaurus/D76D74",
  "Heck": "http://data.archaeology.link/data/maritimethesaurus/338D81",
  "Holznagel": "http://data.archaeology.link/data/maritimethesaurus/78E36E",
  "Holzstift": "http://data.archaeology.link/data/maritimethesaurus/27CABE",
  "Jungfer-Block": "http://data.archaeology.link/data/maritimethesaurus/241F5C",
  "Kabine": "http://data.archaeology.link/data/maritimethesaurus/9272A2",
  "Kaffe": "http://data.archaeology.link/data/maritimethesaurus/6A3CBB",
  "Kalfat": "http://data.archaeology.link/data/maritimethesaurus/E1F036",
  "Kanuausleger": "http://data.archaeology.link/data/maritimethesaurus/71B0DA",
  "Keipe": "http://data.archaeology.link/data/maritimethesaurus/C84B3B",
  "Kiel": "http://data.archaeology.link/data/maritimethesaurus/72AED5",
  "Kielgang": "http://data.archaeology.link/data/maritimethesaurus/8ABF23",
  "Kielplanke": "http://data.archaeology.link/data/maritimethesaurus/918C08",
  "Kielschwein": "http://data.archaeology.link/data/maritimethesaurus/F95C88",
  "Kimm (Eckig)": "http://data.archaeology.link/data/maritimethesaurus/781A6E",
  "Kimm (Rund)": "http://data.archaeology.link/data/maritimethesaurus/6BA6CF",
  "Kimmholz": "http://data.archaeology.link/data/maritimethesaurus/01F313",
  "Kimmstringer": "http://data.archaeology.link/data/maritimethesaurus/C8E484",
  "Klampe": "http://data.archaeology.link/data/maritimethesaurus/9F2983",
  "Klinker (Seite)": "http://data.archaeology.link/data/maritimethesaurus/B8CE4C",
  "Knie": "http://data.archaeology.link/data/maritimethesaurus/4F3B14",
  "Kraweel (Beplankung)": "http://data.archaeology.link/data/maritimethesaurus/41597C",
  "Kraweel (Boden)": "http://data.archaeology.link/data/maritimethesaurus/EDCB2D",
  "Kraweel (Seite)": "http://data.archaeology.link/data/maritimethesaurus/3D5B72",
  "Kraweel Beplankt": "http://data.archaeology.link/data/maritimethesaurus/C5510C",
  "K\u00fcste": "http://data.archaeology.link/data/maritimethesaurus/1DF903",
  "Langschiff": "http://data.archaeology.link/data/maritimethesaurus/DA3C3F",
  "Laufplanke": "http://data.archaeology.link/data/maritimethesaurus/4026B3",
  "Lukendeckel": "http://data.archaeology.link/data/maritimethesaurus/E1C71C",
  "L\u00e4ngsversteifung": "http://data.archaeology.link/data/maritimethesaurus/A2C3C4",
  "Mainz A": "http://data.archaeology.link/data/maritimethesaurus/7AC92B",
  "Mainz B": "http://data.archaeology.link/data/maritimethesaurus/407956",
  "Mallenbauweise": "http://data.archaeology.link/data/maritimethesaurus/85E84B",
  "Mast (Besanmast)": "http://data.archaeology.link/data/maritimethesaurus/F4B395",
  "Mast (Hauptmast)": "http://data.archaeology.link/data/maritimethesaurus/6955E7",
  "Mast (Vormast)": "http://data.archaeology.link/data/maritimethesaurus/67971F",
  "Mastbalken": "http://data.archaeology.link/data/maritimethesaurus/4C4634",
  "Mastbereich": "http://data.archaeology.link/data/maritimethesaurus/0741A5",
  "Mastducht": "http://data.archaeology.link/data/maritimethesaurus/6C9F8B",
  "Mastfisch": "http://data.archaeology.link/data/maritimethesaurus/7213DA",
  "Mastspant": "http://data.archaeology.link/data/maritimethesaurus/6D56F8",
  "Mastspur": "http://data.archaeology.link/data/maritimethesaurus/657FC7",
  "Mastst\u00fctze": "http://data.archaeology.link/data/maritimethesaurus/3E51BD",
  "Masttopp": "http://data.archaeology.link/data/maritimethesaurus/4647AA",
  "Milit\u00e4rfahrzeug": "http://data.archaeology.link/data/maritimethesaurus/35DAD4",
  "Mittelsteven": "http://data.archaeology.link/data/maritimethesaurus/E3BAB8",
  "NAVISone Maritime Thesaurus": "http://data.archaeology.link/data/maritimethesaurus/cs01",
  "Nagel": "http://data.archaeology.link/data/maritimethesaurus/4046CE",
  "Nagel (Baum)": "http://data.archaeology.link/data/maritimethesaurus/753375",
  "Nagel (Bronze)": "http://data.archaeology.link/data/maritimethesaurus/82B0C0",
  "Nagel (Kupfer)": "http://data.archaeology.link/data/maritimethesaurus/A18262",
  "Naht": "http://data.archaeology.link/data/maritimethesaurus/4156FE",
  "Nahtspant": "http://data.archaeology.link/data/maritimethesaurus/BF0944",
  "Navis caudicaria": "http://data.archaeology.link/data/maritimethesaurus/07E13E",
  "Navis oneraria": "http://data.archaeology.link/data/maritimethesaurus/6B2266",
  "Niet": "http://data.archaeology.link/data/maritimethesaurus/92A980",
  "Nordic": "http://data.archaeology.link/data/maritimethesaurus/299329",
  "North Ferriby": "http://data.archaeology.link/data/maritimethesaurus/A3F079",
  "Nut und Feder": "http://data.archaeology.link/data/maritimethesaurus/D7D714",
  "Obersporn": "http://data.archaeology.link/data/maritimethesaurus/5C8CF5",
  "Oberstimm": "http://data.archaeology.link/data/maritimethesaurus/C0F289",
  "Paddel": "http://data.archaeology.link/data/maritimethesaurus/8BF813",
  "Papyrusboot": "http://data.archaeology.link/data/maritimethesaurus/988120",
  "Planke": "http://data.archaeology.link/data/maritimethesaurus/EAE76A",
  "Plankenbeschlag": "http://data.archaeology.link/data/maritimethesaurus/1051B8",
  "Poller": "http://data.archaeology.link/data/maritimethesaurus/E6E992",
  "Pommeroeul 1": "http://data.archaeology.link/data/maritimethesaurus/A35B7B",
  "Querriegel": "http://data.archaeology.link/data/maritimethesaurus/C873D9",
  "Rack": "http://data.archaeology.link/data/maritimethesaurus/E98761",
  "Rad": "http://data.archaeology.link/data/maritimethesaurus/1BEB77",
  "Rah": "http://data.archaeology.link/data/maritimethesaurus/D270FA",
  "Rammsporn": "http://data.archaeology.link/data/maritimethesaurus/172BD7",
  "Reling": "http://data.archaeology.link/data/maritimethesaurus/CFF6DF",
  "Riemen": "http://data.archaeology.link/data/maritimethesaurus/BC051E",
  "Riemenpforte": "http://data.archaeology.link/data/maritimethesaurus/6FDEE8",
  "Ruder (Heck)": "http://data.archaeology.link/data/maritimethesaurus/01E22C",
  "Ruderbalken": "http://data.archaeology.link/data/maritimethesaurus/E865A5",
  "Ruderbalken St\u00fctze": "http://data.archaeology.link/data/maritimethesaurus/33BF0F",
  "Ruderducht (Sitz)": "http://data.archaeology.link/data/maritimethesaurus/C64348",
  "Ruderfassung": "http://data.archaeology.link/data/maritimethesaurus/5FA6B8",
  "Ruderpinne": "http://data.archaeology.link/data/maritimethesaurus/1C02BA",
  "Ruderverblendung": "http://data.archaeology.link/data/maritimethesaurus/287711",
  "Rute": "http://data.archaeology.link/data/maritimethesaurus/534E87",
  "Schale": "http://data.archaeology.link/data/maritimethesaurus/31F675",
  "Schalenbauweise": "http://data.archaeology.link/data/maritimethesaurus/980A93",
  "Schandeckel": "http://data.archaeology.link/data/maritimethesaurus/22E3B2",
  "Schanzkleid": "http://data.archaeology.link/data/maritimethesaurus/75B895",
  "Scheuerleiste": "http://data.archaeology.link/data/maritimethesaurus/F7040D",
  "Schild": "http://data.archaeology.link/data/maritimethesaurus/369740",
  "Schildhalterung": "http://data.archaeology.link/data/maritimethesaurus/B44495",
  "Schnur": "http://data.archaeology.link/data/maritimethesaurus/6264CD",
  "Schott": "http://data.archaeology.link/data/maritimethesaurus/9E1A00",
  "Sch\u00e4ftung": "http://data.archaeology.link/data/maritimethesaurus/DFC9A3",
  "See": "http://data.archaeology.link/data/maritimethesaurus/E23219",
  "Segel (Lateiner)": "http://data.archaeology.link/data/maritimethesaurus/247DBF",
  "Segel (Rah)": "http://data.archaeology.link/data/maritimethesaurus/137F48",
  "Segel (Sprit)": "http://data.archaeology.link/data/maritimethesaurus/F4937E",
  "Seitenspant": "http://data.archaeology.link/data/maritimethesaurus/AF97BA",
  "Seitensteven": "http://data.archaeology.link/data/maritimethesaurus/AC499C",
  "Skelettbauweise": "http://data.archaeology.link/data/maritimethesaurus/74E140",
  "Spant": "http://data.archaeology.link/data/maritimethesaurus/7F509F",
  "Spiegel": "http://data.archaeology.link/data/maritimethesaurus/9AF80B",
  "Sponung": "http://data.archaeology.link/data/maritimethesaurus/6B83EA",
  "Sprung": "http://data.archaeology.link/data/maritimethesaurus/CC9873",
  "Stakstange": "http://data.archaeology.link/data/maritimethesaurus/B6DB9B",
  "Steuerruder": "http://data.archaeology.link/data/maritimethesaurus/FE4152",
  "Stevendekoration": "http://data.archaeology.link/data/maritimethesaurus/736CB6",
  "Stevenschuh/Anlauf": "http://data.archaeology.link/data/maritimethesaurus/DBD212",
  "Stringer": "http://data.archaeology.link/data/maritimethesaurus/BA2F0A",
  "St\u00fctze": "http://data.archaeology.link/data/maritimethesaurus/8D3E7D",
  "Tau": "http://data.archaeology.link/data/maritimethesaurus/E4C877",
  "Toppsegel": "http://data.archaeology.link/data/maritimethesaurus/C44B0A",
  "Totgang": "http://data.archaeology.link/data/maritimethesaurus/C18B1B",
  "Treidelpfosten": "http://data.archaeology.link/data/maritimethesaurus/C2BB4F",
  "Typ Blussus": "http://data.archaeology.link/data/maritimethesaurus/50A78E",
  "Typ Igel": "http://data.archaeology.link/data/maritimethesaurus/D15DAB",
  "Typ Neumagen": "http://data.archaeology.link/data/maritimethesaurus/7A68A2",
  "Typ Portus": "http://data.archaeology.link/data/maritimethesaurus/7E27B4",
  "Unbekannt": "http://data.archaeology.link/data/maritimethesaurus/476A2A",
  "Unbekannte Konstruktion": "http://data.archaeology.link/data/maritimethesaurus/2543C0",
  "Unbekannter Antrieb": "http://data.archaeology.link/data/maritimethesaurus/8EF01D",
  "Unbekannter Schiffstyp": "http://data.archaeology.link/data/maritimethesaurus/1C9E02",
  "Utrecht 1": "http://data.archaeology.link/data/maritimethesaurus/14FC5D",
  "Utrecht 3": "http://data.archaeology.link/data/maritimethesaurus/5A3BAE",
  "Vorderkastell": "http://data.archaeology.link/data/maritimethesaurus/88987C",
  "Vordersteven": "http://data.archaeology.link/data/maritimethesaurus/AFBCF2",
  "Vorschiff": "http://data.archaeology.link/data/maritimethesaurus/7BABAD",
  "Vorsegel": "http://data.archaeology.link/data/maritimethesaurus/A46FC5",
  "Waffen": "http://data.archaeology.link/data/maritimethesaurus/045F07",
  "Wegerung": "http://data.archaeology.link/data/maritimethesaurus/08123C",
  "Werkzeugspur": "http://data.archaeology.link/data/maritimethesaurus/AEF1D5",
  "Winde": "http://data.archaeology.link/data/maritimethesaurus/BAC933",
  "Woerden 1": "http://data.archaeology.link/data/maritimethesaurus/85512C",
  "Woerden 2": "http://data.archaeology.link/data/maritimethesaurus/EA28ED",
  "Wrange": "http://data.archaeology.link/data/maritimethesaurus/C747D7",
  "Zimmermannszeichen": "http://data.archaeology.link/data/maritimethesaurus/7BE436",
  "Zwammerdam": "http://data.archaeology.link/data/maritimethesaurus/BEAABB",
  "Zwammerdam 3": "http://data.archaeology.link/data/maritimethesaurus/8A94C2",
  "Zwammerdam 5": "http://data.archaeology.link/data/maritimethesaurus/EECFB0",
  "[Antrieb]": "http://data.archaeology.link/data/maritimethesaurus/1003",
  "[Arbeitsumgebung]": "http://data.archaeology.link/data/maritimethesaurus/1002",
  "[Aufbauten]": "http://data.archaeology.link/data/maritimethesaurus/1019",
  "[Besegelung]": "http://data.archaeology.link/data/maritimethesaurus/1010",
  "[Decks und Weger]": "http://data.archaeology.link/data/maritimethesaurus/1008",
  "[Handhabung]": "http://data.archaeology.link/data/maritimethesaurus/1014",
  "[Innenkonstruktion]": "http://data.archaeology.link/data/maritimethesaurus/1007",
  "[Konstruktionsmerkmale]": "http://data.archaeology.link/data/maritimethesaurus/1009",
  "[Kriegsf\u00fchrung]": "http://data.archaeology.link/data/maritimethesaurus/1015",
  "[Oberfl\u00e4chenbehandlung]": "http://data.archaeology.link/data/maritimethesaurus/1016",
  "[Ruderanlage]": "http://data.archaeology.link/data/maritimethesaurus/1011",
  "[Rudern und paddeln]": "http://data.archaeology.link/data/maritimethesaurus/1012",
  "[Rumpf]": "http://data.archaeology.link/data/maritimethesaurus/1006",
  "[Schiffsfunktion]": "http://data.archaeology.link/data/maritimethesaurus/1001",
  "[Schiffstyp]": "http://data.archaeology.link/data/maritimethesaurus/1004",
  "[Staken und treideln]": "http://data.archaeology.link/data/maritimethesaurus/1013",
  "falscher Kiel": "http://data.archaeology.link/data/maritimethesaurus/DD6037",
  "galeeren\u00e4hnlich": "http://data.archaeology.link/data/maritimethesaurus/31E77B",
  "gebunden": "http://data.archaeology.link/data/maritimethesaurus/E427D1",
  "hulk\u00e4hnlich": "http://data.archaeology.link/data/maritimethesaurus/4E634F",
  "koggen\u00e4hnlich": "http://data.archaeology.link/data/maritimethesaurus/95C02A",
  "n\u00fcstergatt": "http://data.archaeology.link/data/maritimethesaurus/622C3E",
  "prahm\u00e4hnlich": "http://data.archaeology.link/data/maritimethesaurus/22B1CD",
  "wikingerschiff\u00e4hnlich": "http://data.archaeology.link/data/maritimethesaurus/4F19CD"
}